/* ═══════════════════════════════════════════════════════════
   rsi.js  —  RSI study guide (rsi.html)

   The point of this page is a discrepancy found while writing it, so the
   code that demonstrates it lives here rather than in prose.

   candlestick_chart/indicators/rsi.js — and the identical copy in
   routes/screener-technicals.js — computes RSI from a PLAIN SIMPLE
   AVERAGE of gains and losses over the lookback window. Wilder's
   original RSI, which is what TradingView, Investing.com and every
   textbook mean by "RSI(14)", smooths those averages forward instead.
   The two are not equivalent and do not converge.

   Both are implemented below. appRSI() is copied verbatim from the
   app so the comparison is against what actually ships, not against a
   tidied-up version of it. The market-wide size of the gap is read from
   data/learning-stats.json (generated by scripts/build-learning-stats.js,
   which contains the same two functions); the per-stock illustration is
   computed live here from the real price archive.

   Consumed by: rsi.html
   ═══════════════════════════════════════════════════════════ */
'use strict';

const APP_COLOR = '#D77FFF';     // matches RSI_COLOR in indicators/rsi.js
const WILDER_COLOR = '#22d3ee';
const PRICE_COLOR = '#1e88e5';
const GRID = 'rgba(140,150,170,0.30)';

// ─── The app's RSI, ported verbatim from indicators/rsi.js ─────
function appRSI(prices, period = 14) {
  const changes = prices.map((p, i) => (i === 0 ? 0 : p - prices[i - 1]));
  return prices.map((_, i) => {
    if (i < period) return null;
    const slice = changes.slice(i - period + 1, i + 1);
    const gains = slice.filter(c => c > 0).reduce((a, b) => a + b, 0);
    const losses = Math.abs(slice.filter(c => c < 0).reduce((a, b) => a + b, 0));
    const avgG = gains / period;
    const avgL = losses / period;
    const rs = avgL === 0 ? 100 : avgG / avgL;
    return 100 - 100 / (1 + rs);
  });
}

// ─── Wilder's original, for comparison ────────────────────────
// The averages are seeded once from the first `period` changes and then
// carried forward: avg = (avg × (period − 1) + today) / period. Every past
// bar keeps some weight forever, which is the whole difference.
function wilderRSI(prices, period = 14) {
  const out = new Array(prices.length).fill(null);
  let avgG = 0, avgL = 0;
  for (let i = 1; i < prices.length; i++) {
    const d = prices[i] - prices[i - 1];
    const g = Math.max(d, 0), l = Math.max(-d, 0);
    if (i <= period) {
      avgG += g; avgL += l;
      if (i === period) {
        avgG /= period; avgL /= period;
        out[i] = 100 - 100 / (1 + (avgL === 0 ? 100 : avgG / avgL));
      }
    } else {
      avgG = (avgG * (period - 1) + g) / period;
      avgL = (avgL * (period - 1) + l) / period;
      out[i] = 100 - 100 / (1 + (avgL === 0 ? 100 : avgG / avgL));
    }
  }
  return out;
}

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
const f1 = v => (v == null ? '—' : Number(v).toFixed(1));
const f2 = v => (v == null ? '—' : Number(v).toFixed(2));
const n0 = v => (v == null ? '—' : Math.round(v).toLocaleString());

function fmtDate(d) {
  const [y, m, day] = String(d).split('/');
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const mi = parseInt(m, 10) - 1;
  return mi >= 0 && mi < 12 ? `${day} ${months[mi]} ${y}` : d;
}

// ─── The RSI pane, drawn twice on one axis ────────────────────
function rsiPaneSVG(seriesA, seriesB, opts = {}) {
  const w = opts.w ?? 620, h = opts.h ?? 190;
  const padL = 8, padR = 34, padT = 8, padB = 8;
  const plotW = w - padL - padR, plotH = h - padT - padB;
  const n = seriesA.length;
  const x = i => padL + (plotW * i) / Math.max(1, n - 1);
  const y = v => padT + plotH * (1 - v / 100);

  const band = `
    <rect x="${padL}" y="${y(100)}" width="${plotW}" height="${y(70) - y(100)}"
          fill="#ef5350" opacity="0.07" />
    <rect x="${padL}" y="${y(30)}" width="${plotW}" height="${y(0) - y(30)}"
          fill="#26a69a" opacity="0.07" />`;

  const grid = [30, 50, 70].map(lv => `
    <line x1="${padL}" y1="${y(lv)}" x2="${w - padR}" y2="${y(lv)}"
          stroke="${GRID}" stroke-width="1" stroke-dasharray="${lv === 50 ? '2 4' : '4 3'}" />
    <text x="${w - padR + 5}" y="${y(lv) + 3}" class="cd-fig-label">${lv}</text>`).join('');

  const path = (series, color, dash) => {
    const pts = series.map((v, i) => (v == null ? null : `${x(i)},${y(v)}`))
      .filter(Boolean).join(' ');
    return `<polyline points="${pts}" fill="none" stroke="${color}" stroke-width="1.7"
              stroke-linejoin="round" stroke-linecap="round"
              ${dash ? `stroke-dasharray="${dash}"` : ''} />`;
  };

  return `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}" role="img"
               class="cd-svg" preserveAspectRatio="none">
    ${band}${grid}
    ${path(seriesB, WILDER_COLOR, '5 3')}
    ${path(seriesA, APP_COLOR)}
  </svg>`;
}

function priceSVG(closes, opts = {}) {
  const w = opts.w ?? 620, h = opts.h ?? 90;
  const padL = 8, padR = 34, padT = 8, padB = 8;
  const plotW = w - padL - padR, plotH = h - padT - padB;
  const lo = Math.min(...closes), hi = Math.max(...closes);
  const span = (hi - lo) || 1;
  const x = i => padL + (plotW * i) / Math.max(1, closes.length - 1);
  const y = v => padT + plotH * (1 - (v - lo) / span);
  const pts = closes.map((v, i) => `${x(i)},${y(v)}`).join(' ');
  return `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}" role="img"
               class="cd-svg" preserveAspectRatio="none">
    <polyline points="${pts}" fill="none" stroke="${PRICE_COLOR}" stroke-width="1.6"
              stroke-linejoin="round" stroke-linecap="round"/>
    <text x="${w - padR + 5}" y="${y(hi) + 4}" class="cd-fig-label">${hi.toFixed(0)}</text>
    <text x="${w - padR + 5}" y="${y(lo) + 4}" class="cd-fig-label">${lo.toFixed(0)}</text>
  </svg>`;
}

// ─── Live worked example on a real stock ──────────────────────
const EXAMPLE_CODE = 'SQURPHARMA'; // large, liquid, long history — not chosen for its result
const EXAMPLE_BARS = 260;

async function loadExample() {
  const host = document.getElementById('rsi-example');
  if (!host) return;
  try {
    const res = await fetch(`/historical_prices/json_files/${EXAMPLE_CODE}.json`);
    if (!res.ok) throw new Error(String(res.status));
    const raw = await res.json();
    const rows = raw
      .filter(r => r.Close > 0)
      .sort((a, b) => (a.Date < b.Date ? -1 : a.Date > b.Date ? 1 : 0));

    // Both series are computed on the FULL history, then sliced for display.
    // Wilder's is path-dependent — seeding it from a 260-bar window would
    // give a different line than the chart shows, which is the one mistake
    // this whole page is about not making.
    const closes = rows.map(r => r.Close);
    const a = appRSI(closes), wl = wilderRSI(closes);
    const from = Math.max(0, closes.length - EXAMPLE_BARS);
    const sliceA = a.slice(from), sliceW = wl.slice(from);
    const sliceC = closes.slice(from), sliceD = rows.slice(from).map(r => r.Date);

    // Widest disagreement inside the displayed window.
    let maxI = -1, maxD = -1;
    for (let i = 0; i < sliceA.length; i++) {
      if (sliceA[i] == null || sliceW[i] == null) continue;
      const d = Math.abs(sliceA[i] - sliceW[i]);
      if (d > maxD) { maxD = d; maxI = i; }
    }
    // Bars where the two implementations disagree about overbought/oversold.
    let disagree = 0, judged = 0;
    for (let i = 0; i < sliceA.length; i++) {
      if (sliceA[i] == null || sliceW[i] == null) continue;
      judged++;
      const za = sliceA[i] > 70 ? 1 : sliceA[i] < 30 ? -1 : 0;
      const zw = sliceW[i] > 70 ? 1 : sliceW[i] < 30 ? -1 : 0;
      if (za !== zw) disagree++;
    }

    const last = sliceA.length - 1;
    host.innerHTML = `
      <div style="width:100%">
        <div class="cd-metrics">
          <span>${esc(EXAMPLE_CODE)} · last <b>${EXAMPLE_BARS}</b> sessions</span>
          <span>This app <b style="color:${APP_COLOR}">${f2(sliceA[last])}</b></span>
          <span>Wilder <b style="color:${WILDER_COLOR}">${f2(sliceW[last])}</b></span>
          <span>Widest gap here <b class="cd-bad">${f1(maxD)} pts</b></span>
          <span>Zone verdict differs <b>${f1((100 * disagree) / Math.max(1, judged))}%</b> of bars</span>
        </div>
        ${priceSVG(sliceC)}
        ${rsiPaneSVG(sliceA, sliceW)}
        <div class="cd-anat-row" style="margin-top:12px">
          <span class="cd-anat-key" style="color:${APP_COLOR}">Solid</span>
          <span>RSI(14) exactly as this app computes it — a simple average of the last 14
          gains and losses.</span>
        </div>
        <div class="cd-anat-row">
          <span class="cd-anat-key" style="color:${WILDER_COLOR}">Dashed</span>
          <span>Wilder's RSI(14) on the same closes — what a TradingView chart of
          ${esc(EXAMPLE_CODE)} would show.</span>
        </div>
        ${maxI >= 0 ? `
        <div class="cd-anat-row">
          <span class="cd-anat-key">Worst bar</span>
          <span><b>${esc(fmtDate(sliceD[maxI]))}</b> — this app read
          <b>${f1(sliceA[maxI])}</b>, Wilder's read <b>${f1(sliceW[maxI])}</b>. Same closing
          prices, same period, ${f1(maxD)} points apart.</span>
        </div>` : ''}
      </div>`;
  } catch {
    host.innerHTML = `<div class="cd-callout">Couldn't load real price data for this section
      (needs this app's own dev server serving <code>/historical_prices/</code>).</div>`;
  }
}

// ─── Market-wide figures from the generated stats ─────────────
async function loadStats() {
  const host = document.getElementById('rsi-marketwide');
  if (!host) return;
  let stats;
  try {
    const res = await fetch('/data/learning-stats.json');
    if (!res.ok) throw new Error(String(res.status));
    stats = await res.json();
  } catch {
    host.innerHTML = `<div class="cd-callout">Couldn't load <code>/data/learning-stats.json</code>.
      Run <code>node scripts/build-learning-stats.js</code> to generate it.</div>`;
    return;
  }
  const r = stats.rsi;
  if (!r) return;

  host.innerHTML = `
    <div class="cd-metrics">
      <span>Stocks <b>${n0(r.stocks)}</b></span>
      <span>Bars compared <b>${n0(r.comparisons)}</b></span>
      <span>Archive <b>${esc(stats.archive.dateFrom)} → ${esc(stats.archive.dateTo)}</b></span>
    </div>
    <div class="cd-table-wrap">
      <table class="cd-table">
        <thead><tr><th>Measure</th><th>This app</th><th>Wilder's</th><th>What it means</th></tr></thead>
        <tbody>
          <tr>
            <td class="cd-t-name">Median difference</td>
            <td colspan="2"><b class="cd-bad">${f2(r.medianAbsDiff)} points</b></td>
            <td class="cd-t-why">Half of all bars differ by more than this. On a 0–100 scale
                that is not a rounding artefact.</td>
          </tr>
          <tr>
            <td class="cd-t-name">90th percentile</td>
            <td colspan="2"><b>${f2(r.p90AbsDiff)} points</b></td>
            <td class="cd-t-why">One bar in ten differs by at least this much.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Largest difference</td>
            <td colspan="2"><b>${f2(r.maxAbsDiff)} points</b></td>
            <td class="cd-t-why">The two readings can land at opposite ends of the pane on the
                same bar.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Bars read "overbought"</td>
            <td><b>${f1(r.appOverboughtPct)}%</b></td>
            <td><b>${f1(r.wilderOverboughtPct)}%</b></td>
            <td class="cd-t-why">This app calls overbought roughly
                ${f1(r.appOverboughtPct / Math.max(0.1, r.wilderOverboughtPct))}× as often as
                the standard version does.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Bars read "oversold"</td>
            <td><b>${f1(r.appOversoldPct)}%</b></td>
            <td><b>${f1(r.wilderOversoldPct)}%</b></td>
            <td class="cd-t-why">Same pattern on the downside.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Verdict disagrees</td>
            <td colspan="2"><b class="cd-bad">${f1(r.zoneDisagreePct)}% of bars</b></td>
            <td class="cd-t-why">On roughly one bar in ${Math.round(100 / Math.max(0.1, r.zoneDisagreePct))},
                the two implementations put price in different zones — overbought vs neutral,
                or neutral vs oversold.</td>
          </tr>
        </tbody>
      </table>
    </div>`;
}

document.addEventListener('DOMContentLoaded', () => {
  loadExample();
  loadStats();

  const links = [...document.querySelectorAll('.cd-toc a')];
  const targets = links.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  if (targets.length && 'IntersectionObserver' in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (!e.isIntersecting) return;
        links.forEach(a => a.classList.toggle('active', a.getAttribute('href') === '#' + e.target.id));
      });
    }, { rootMargin: '-20% 0px -70% 0px' });
    targets.forEach(t => io.observe(t));
  }
});
