/* ═══════════════════════════════════════════════════════════
   sector-guide.js  —  shared renderer for the five sector guides
   (insurance / textile / telecom / paper / pharma .html)

   ONE renderer rather than five, for the same reason guide.css is one
   stylesheet: the sector pages differ in their prose, not in what they
   measure. Restyling or correcting the measurement here corrects it on
   all five, and a sixth sector page needs only an HTML file.

   Each page declares what it covers before loading this script:

     window.SECTOR_GUIDE = { sectors: ['Insurance', 'Life Insurance'] };

   Everything numeric comes from data/learning-stats.json, generated by
   scripts/build-learning-stats.js from this app's own price archive.
   Nothing here is typed into a page — regenerate the file and every
   sector guide updates, including the comparisons between them.

   WHAT THESE PAGES ARE NOT. Descriptive statistics about how a group of
   listed companies has traded. Not valuations, not forecasts, not
   recommendations, and — because the archive holds prices, not accounts
   — not fundamental analysis. Each page says so in its own words too.
   ═══════════════════════════════════════════════════════════ */
'use strict';

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
const f1 = v => (v == null ? '—' : Number(v).toFixed(1));
const f2 = v => (v == null ? '—' : Number(v).toFixed(2));
const n0 = v => (v == null ? '—' : Math.round(v).toLocaleString());

/** Percent, signed and coloured — the sector tables are full of these. */
function pct(v) {
  if (v == null) return '<span class="cd-t-why">—</span>';
  const cls = v > 0 ? 'cd-good' : v < 0 ? 'cd-bad' : '';
  return `<b class="${cls}">${v > 0 ? '+' : ''}${Number(v).toFixed(1)}%</b>`;
}

/** Taka turnover, abbreviated — raw figures run to nine digits. */
function taka(v) {
  if (v == null) return '—';
  if (v >= 1e7) return `৳${(v / 1e7).toFixed(2)} cr`;
  if (v >= 1e5) return `৳${(v / 1e5).toFixed(2)} lakh`;
  return `৳${Math.round(v).toLocaleString()}`;
}

/** How this sector's figure compares with the all-market median. */
function vsMarket(sectorVal, marketVal, unit = 'pp') {
  if (sectorVal == null || marketVal == null) return '';
  const d = sectorVal - marketVal;
  const cls = d > 0 ? 'cd-good' : d < 0 ? 'cd-bad' : '';
  return `<span class="${cls}">${d > 0 ? '+' : ''}${d.toFixed(1)} ${unit} vs market</span>`;
}

// ─── Snapshot: the sector in one strip, against the whole market ───
function snapshotHTML(s, market) {
  return `
    <div class="cd-table-wrap">
      <table class="cd-table">
        <thead><tr><th>Measure</th><th>${esc(s.sector)}</th><th>All-market median</th><th>Read</th></tr></thead>
        <tbody>
          <tr>
            <td class="cd-t-name">Listed stocks</td>
            <td class="cd-num"><b>${n0(s.stocks)}</b></td>
            <td class="cd-num">${n0(market.stocks)} total</td>
            <td class="cd-t-why">${f1((100 * s.stocks) / market.stocks)}% of the operating-company
                universe by count.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median 1-year return</td>
            <td class="cd-num">${pct(s.medChg1y)}</td>
            <td class="cd-num">${pct(market.medChg1y)}</td>
            <td class="cd-t-why">${vsMarket(s.medChg1y, market.medChg1y)}</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median 3-year return</td>
            <td class="cd-num">${pct(s.medChg3y)}</td>
            <td class="cd-num">${pct(market.medChg3y)}</td>
            <td class="cd-t-why">${vsMarket(s.medChg3y, market.medChg3y)}</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median 5-year return</td>
            <td class="cd-num">${pct(s.medChg5y)}</td>
            <td class="cd-num">${pct(market.medChg5y)}</td>
            <td class="cd-t-why">${vsMarket(s.medChg5y, market.medChg5y)}</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median volatility</td>
            <td class="cd-num"><b>${f1(s.medVol1y)}%</b></td>
            <td class="cd-num">${f1(market.medVol1y)}%</td>
            <td class="cd-t-why">Annualised from a year of daily closes.
                ${vsMarket(s.medVol1y, market.medVol1y)}</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median daily turnover</td>
            <td class="cd-num"><b>${taka(s.medTurnover)}</b></td>
            <td class="cd-num">${taka(market.medTurnover)}</td>
            <td class="cd-t-why">The typical stock's typical day. Liquidity, not size.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Median distance below 52-week high</td>
            <td class="cd-num"><b>${f1(s.medBelowHigh)}%</b></td>
            <td class="cd-num">${f1(market.medBelowHigh)}%</td>
            <td class="cd-t-why">Where the sector sits inside its own recent range.</td>
          </tr>
          <tr>
            <td class="cd-t-name">Market categories</td>
            <td class="cd-num"><b>A ${s.catA} · B ${s.catB} · N ${s.catN} · Z ${s.catZ}</b></td>
            <td class="cd-num">—</td>
            <td class="cd-t-why">Z means the company failed to hold an AGM or declare a dividend.
                ${s.catZ ? `<b class="cd-bad">${s.catZ} of ${s.stocks} here are Z.</b>` : 'None here are Z.'}</td>
          </tr>
          <tr>
            <td class="cd-t-name">Recent cash dividend payers</td>
            <td class="cd-num"><b>${s.payers} of ${s.stocks}</b></td>
            <td class="cd-num">—</td>
            <td class="cd-t-why">Declared a cash dividend for one of the last two completed
                years, per <code>data/dividends.json</code>.</td>
          </tr>
        </tbody>
      </table>
    </div>`;
}

// ─── Where the sector sits among all sectors ───────────────────
function rankingHTML(ranking, mine) {
  const rows = ranking.map((s, i) => {
    const here = mine.includes(s.sector);
    return `<tr${here ? ' style="background:var(--accent-dim)"' : ''}>
      <td class="cd-num">${i + 1}</td>
      <td class="${here ? 'cd-t-name' : ''}">${here ? '<b>' : ''}${esc(s.sector)}${here ? '</b>' : ''}</td>
      <td class="cd-num">${n0(s.stocks)}</td>
      <td class="cd-num">${pct(s.medChg1y)}</td>
      <td class="cd-num">${pct(s.medChg3y)}</td>
      <td class="cd-num">${f1(s.medVol1y)}%</td>
      <td class="cd-num">${taka(s.medTurnover)}</td>
    </tr>`;
  }).join('');

  return `
    <div class="cd-table-wrap">
      <table class="cd-table">
        <thead><tr>
          <th>#</th><th>Sector</th><th>Stocks</th><th>Median 1y</th>
          <th>Median 3y</th><th>Median vol</th><th>Median turnover</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

// ─── Constituents ──────────────────────────────────────────────
function constituentsHTML(s, names) {
  const rows = s.constituents.map(c => {
    const shortHistory = c.chg5y == null;
    return `<tr>
      <td class="cd-t-name">${esc(c.code)}</td>
      <td class="cd-t-why">${esc(names[c.code] || '')}</td>
      <td class="cd-num">${c.category ? esc(c.category) : '—'}</td>
      <td class="cd-num">${f2(c.last)}</td>
      <td class="cd-num">${pct(c.chg1y)}</td>
      <td class="cd-num">${pct(c.chg3y)}</td>
      <td class="cd-num">${pct(c.chg5y)}</td>
      <td class="cd-num">${f1(c.vol1y)}%</td>
      <td class="cd-num">${f1(c.pctBelowHigh)}%</td>
      <td class="cd-num">${taka(c.medTurnover)}</td>
      <td class="cd-num">${c.divPct != null ? `${c.divPct}% <span class="cd-t-why">${c.divYear}</span>` : '<span class="cd-t-why">none</span>'}</td>
      <td class="cd-t-why">${shortHistory ? `from ${esc(c.firstDate)}` : ''}</td>
    </tr>`;
  }).join('');

  return `
    <div class="cd-table-wrap">
      <table class="cd-table" style="min-width:1080px">
        <thead><tr>
          <th>Code</th><th>Company</th><th>Cat</th><th>Last</th><th>1y</th><th>3y</th><th>5y</th>
          <th>Vol</th><th>Off high</th><th>Median turnover</th><th>Last cash div</th><th></th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
    <p class="cd-foot" style="margin-top:14px">
      Sorted by median daily turnover — most traded first. A dash under 3y or 5y means the
      archive does not reach back that far for that listing, rather than a return of zero;
      the last column shows where its history starts. Returns are price only: cash dividends
      received are not added back, so a steady high-yield payer looks worse here than a
      total-return figure would show.
    </p>`;
}

// ─── Boot ──────────────────────────────────────────────────────
async function renderSectorGuide() {
  const cfg = window.SECTOR_GUIDE || {};
  const wanted = cfg.sectors || [];
  const host = document.getElementById('sec-data');
  if (!host) return;

  let stats;
  try {
    const res = await fetch('/data/learning-stats.json');
    if (!res.ok) throw new Error(String(res.status));
    stats = await res.json();
  } catch {
    host.innerHTML = `<div class="cd-callout">Couldn't load
      <code>/data/learning-stats.json</code>. Generate it with
      <code>node scripts/build-learning-stats.js</code>, and serve the app from its own dev
      server so the file is reachable.</div>`;
    return;
  }

  // Full company names are a nicety, not a requirement — the tables are
  // keyed by ticker and render fine without the app running.
  let names = {};
  try {
    const res = await fetch('/api/company-names');
    // The route wraps the map in { names: {...} }; tolerate a bare map too.
    if (res.ok) { const j = await res.json(); names = j.names || j || {}; }
  } catch { /* ticker-only it is */ }

  const parts = [];
  for (const name of wanted) {
    const s = stats.sectors[name];
    if (!s) {
      parts.push(`<div class="cd-callout">No generated stats for <b>${esc(name)}</b>.</div>`);
      continue;
    }
    parts.push(`
      ${wanted.length > 1 ? `<h3 style="font-family:var(--mono);font-size:15px;margin:8px 0 12px">
        ${esc(s.sector)} — ${s.stocks} listed</h3>` : ''}
      ${snapshotHTML(s, stats.market)}
      <h3 style="font-family:var(--mono);font-size:14px;margin:26px 0 10px">
        Every ${esc(s.sector)} stock in the archive</h3>
      ${constituentsHTML(s, names)}
      ${wanted.length > 1 ? '<div style="height:34px"></div>' : ''}`);
  }
  host.innerHTML = parts.join('');

  const rankHost = document.getElementById('sec-ranking');
  if (rankHost) rankHost.innerHTML = rankingHTML(stats.sectorRanking, wanted);

  const stamp = document.getElementById('sec-generated');
  if (stamp) {
    const d = new Date(stats.generatedAt);
    stamp.innerHTML = `Generated <b>${d.toLocaleDateString(undefined,
      { day: 'numeric', month: 'short', year: 'numeric' })}</b> by
      <code>scripts/build-learning-stats.js</code> from ${n0(stats.archive.stocks)} stocks of
      daily price history, ${esc(stats.archive.dateFrom)} → ${esc(stats.archive.dateTo)}.
      Re-run it and every figure on this page moves with it.`;
  }
}

document.addEventListener('DOMContentLoaded', () => {
  renderSectorGuide();

  const links = [...document.querySelectorAll('.cd-toc a')];
  const targets = links.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  if (targets.length && 'IntersectionObserver' in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (!e.isIntersecting) return;
        links.forEach(a => a.classList.toggle('active', a.getAttribute('href') === '#' + e.target.id));
      });
    }, { rootMargin: '-20% 0px -70% 0px' });
    targets.forEach(t => io.observe(t));
  }
});
