/* ═══════════════════════════════════════════════════════════
   smart-money.js  —  Smart Money Concepts & footprint study guide
   (smart-money.html)

   Two things this page has to keep separate, and the reason it exists:

   1. WHAT THIS APP ACTUALLY IMPLEMENTS. Exactly one SMC idea is coded
      anywhere in this codebase — the liquidity sweep detector in
      routes/super-model-engine.js. Its rule is ported verbatim below so
      the diagram on the page is drawn by the same logic that fires the
      signal, not by an artist's impression of one.

   2. WHAT THE DATA CANNOT SUPPORT. A footprint chart needs per-trade
      bid/ask classification. The archive is daily OHLCV. No amount of
      presentation makes one into the other, so the page says so and
      shows the exact field list instead of implying otherwise.

   Every measured figure on the page is read from data/learning-stats.json
   (generated by scripts/build-learning-stats.js) rather than typed into
   the markup, so re-running the generator updates the prose's numbers
   instead of silently contradicting them.

   Consumed by: smart-money.html
   ═══════════════════════════════════════════════════════════ */
'use strict';

const UP = '#26a69a';
const DOWN = '#ef5350';
const ZONE = '#00d4ff';
const SWEEP = '#f57c00';

// ─── The app's own liquidity-sweep rule, ported verbatim ───────
// From routes/super-model-engine.js: a bar whose wick pushes past the
// prior 20 bars' extreme by more than 0.1%, but which then closes back
// inside that range.
const LIQUIDITY_LOOKBACK = 20;
const LIQUIDITY_MIN_SWEEP_PCT = 0.1;

function detectSweep(bars, i) {
  if (i < LIQUIDITY_LOOKBACK) return null;
  let recentHigh = -Infinity, recentLow = Infinity;
  for (let j = i - LIQUIDITY_LOOKBACK; j < i; j++) {
    if (bars[j].High > recentHigh) recentHigh = bars[j].High;
    if (bars[j].Low < recentLow) recentLow = bars[j].Low;
  }
  const tol = LIQUIDITY_MIN_SWEEP_PCT / 100;
  const cur = bars[i];
  if (cur.High > recentHigh * (1 + tol) && cur.Close < recentHigh) {
    return { dir: 'bearish', level: recentHigh };
  }
  if (cur.Low < recentLow * (1 - tol) && cur.Close > recentLow) {
    return { dir: 'bullish', level: recentLow };
  }
  return null;
}

// ─── The fair-value-gap definition, matching the generator ─────
// Same three-bar test scripts/build-learning-stats.js counts with, so the
// diagram and the measured table below it cannot drift apart.
function findFVG(bars, i) {
  const prev = bars[i - 1], next = bars[i + 1];
  if (!prev || !next) return null;
  if (next.Low > prev.High) return { dir: 'bull', bottom: prev.High, top: next.Low };
  if (next.High < prev.Low) return { dir: 'bear', bottom: next.High, top: prev.Low };
  return null;
}

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
const n0 = v => (v == null ? '—' : Math.round(v).toLocaleString());
const f1 = v => (v == null ? '—' : Number(v).toFixed(1));

// ─── Candle renderer ───────────────────────────────────────────
/** Same approach as candles.js: diagrams are drawn from OHLC, never posed. */
function candleSVG(candles, opts = {}) {
  const w = opts.w ?? (candles.length * 40 + 40);
  const h = opts.h ?? 180;
  const pad = opts.pad ?? 16;
  const lo = Math.min(...candles.map(c => c.l));
  const hi = Math.max(...candles.map(c => c.h));
  const span = (hi - lo) || 1;
  const top = hi + span * 0.08, bot = lo - span * 0.08;
  const y = v => pad + (h - pad * 2) * (1 - (v - bot) / ((top - bot) || 1));

  const slot = (w - pad * 2) / candles.length;
  const bodyW = Math.min(20, slot * 0.55);

  // Shaded bands (a gap, or a swept level's range) go under the candles.
  const bands = (opts.bands || []).map(b => {
    const yTop = y(b.top), yBot = y(b.bottom);
    return `
      <rect x="${pad * 0.4}" y="${yTop}" width="${w - pad * 0.8}" height="${Math.max(1.5, yBot - yTop)}"
            fill="${b.color || ZONE}" opacity="0.16" />
      <line x1="${pad * 0.4}" y1="${yTop}" x2="${w - pad * 0.4}" y2="${yTop}"
            stroke="${b.color || ZONE}" stroke-width="1" stroke-dasharray="3 3" opacity="0.9" />
      <line x1="${pad * 0.4}" y1="${yBot}" x2="${w - pad * 0.4}" y2="${yBot}"
            stroke="${b.color || ZONE}" stroke-width="1" stroke-dasharray="3 3" opacity="0.9" />
      ${b.label ? `<text x="${w - pad * 0.5}" y="${yTop - 4}" text-anchor="end"
            class="cd-fig-label">${esc(b.label)}</text>` : ''}`;
  }).join('');

  const lines = (opts.levels || []).map(l => `
      <line x1="${pad * 0.4}" y1="${y(l.value)}" x2="${w - pad * 0.4}" y2="${y(l.value)}"
            stroke="${l.color || SWEEP}" stroke-width="1.2" stroke-dasharray="4 3" opacity="0.95" />
      ${l.label ? `<text x="${pad * 0.6}" y="${y(l.value) - 4}" class="cd-fig-label">${esc(l.label)}</text>` : ''}`
  ).join('');

  const parts = candles.map((c, i) => {
    const cx = pad + slot * (i + 0.5);
    const rising = c.c >= c.o;
    const col = c.color || (rising ? UP : DOWN);
    const yO = y(c.o), yC = y(c.c);
    const bodyTop = Math.min(yO, yC);
    const bodyH = Math.max(1.5, Math.abs(yC - yO));
    return `
      <line x1="${cx}" y1="${y(c.h)}" x2="${cx}" y2="${y(c.l)}" stroke="${col}" stroke-width="1.5" />
      <rect x="${cx - bodyW / 2}" y="${bodyTop}" width="${bodyW}" height="${bodyH}"
            fill="${col}" stroke="${col}" stroke-width="1.5" rx="0.5" />
      ${c.label ? `<text x="${cx}" y="${h - 3}" text-anchor="middle" class="cd-fig-label">${esc(c.label)}</text>` : ''}`;
  }).join('');

  return `<svg viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" role="img" class="cd-svg">
    ${bands}${lines}${parts}</svg>`;
}

// ─── Diagram 1: a fair value gap, detected not posed ───────────
function drawFVGDiagram() {
  const host = document.getElementById('smc-fvg-fig');
  if (!host) return;
  // Three bars where bar 3's low sits clearly above bar 1's high.
  const bars = [
    { Open: 100, High: 102, Low: 99, Close: 101.5 },
    { Open: 102, High: 109, Low: 101.8, Close: 108.5 },
    { Open: 108.8, High: 111, Low: 104, Close: 110 },
  ];
  const gap = findFVG(bars, 1);
  const candles = bars.map((b, i) => ({
    o: b.Open, h: b.High, l: b.Low, c: b.Close,
    label: ['bar 1', 'bar 2', 'bar 3'][i],
  }));
  host.innerHTML = candleSVG(candles, {
    w: 260, h: 200,
    bands: gap ? [{ top: gap.top, bottom: gap.bottom, label: 'the gap' }] : [],
  });
  const note = document.getElementById('smc-fvg-note');
  if (note && gap) {
    const size = ((gap.top - gap.bottom) / bars[1].Close) * 100;
    note.textContent = `Bar 1's high is ${gap.bottom.toFixed(2)} and bar 3's low is `
      + `${gap.top.toFixed(2)}, so the two never traded at the same price. `
      + `The untraded band is ${(gap.top - gap.bottom).toFixed(2)} wide — `
      + `${size.toFixed(1)}% of bar 2's close.`;
  }
}

// ─── Diagram 2: the liquidity sweep this app really detects ────
function drawSweepDiagram() {
  const host = document.getElementById('smc-sweep-fig');
  if (!host) return;

  // A 20-bar range that drifts sideways, then one bar that wicks through
  // the top of it and closes back inside. The detector below decides
  // whether it qualifies — the diagram does not assume it.
  const bars = [];
  for (let i = 0; i < LIQUIDITY_LOOKBACK; i++) {
    const base = 100 + Math.sin(i / 2.2) * 2.4;
    bars.push({ Open: base, High: base + 1.1, Low: base - 1.1, Close: base + 0.3 });
  }
  const recentHigh = Math.max(...bars.map(b => b.High));
  bars.push({ Open: recentHigh - 0.6, High: recentHigh * 1.02, Low: recentHigh - 2.2, Close: recentHigh - 1.6 });

  const hit = detectSweep(bars, bars.length - 1);

  // Only the tail is legible at this width; the detector still ran on all 21.
  const shown = bars.slice(-9);
  const candles = shown.map((b, i) => ({
    o: b.Open, h: b.High, l: b.Low, c: b.Close,
    color: i === shown.length - 1 && hit ? SWEEP : undefined,
  }));
  host.innerHTML = candleSVG(candles, {
    w: 320, h: 200,
    levels: hit ? [{ value: hit.level, label: `20-bar high ${hit.level.toFixed(2)}` }] : [],
  });

  const note = document.getElementById('smc-sweep-note');
  if (note) {
    note.textContent = hit
      ? `The final bar's high pushed ${(((bars[bars.length - 1].High / hit.level) - 1) * 100).toFixed(2)}% `
        + `past the prior ${LIQUIDITY_LOOKBACK}-bar high of ${hit.level.toFixed(2)} — above the `
        + `${LIQUIDITY_MIN_SWEEP_PCT}% threshold — then closed back below it at `
        + `${bars[bars.length - 1].Close.toFixed(2)}. This app's engine records that as a `
        + `${hit.dir} liquidity sweep.`
      : 'On these bars the rule did not fire.';
  }
}

// ─── Measured sections, read from the generated stats ──────────
async function loadStats() {
  let stats;
  try {
    const res = await fetch('/data/learning-stats.json');
    if (!res.ok) throw new Error(String(res.status));
    stats = await res.json();
  } catch {
    const msg = `<div class="cd-callout">Couldn't load <code>/data/learning-stats.json</code>.
      Run <code>node scripts/build-learning-stats.js</code> and serve the app from its own
      dev server to see the measured figures here.</div>`;
    ['smc-fvg-measured', 'smc-block-table'].forEach(id => {
      const el = document.getElementById(id);
      if (el) el.innerHTML = msg;
    });
    return;
  }

  renderFVGMeasured(stats);
  renderBlockTable(stats);
  stampGenerated(stats);
}

function renderFVGMeasured(stats) {
  const host = document.getElementById('smc-fvg-measured');
  const g = stats.fairValueGaps;
  if (!host || !g) return;

  const rows = Object.entries(g.fillRate).map(([bars, r]) => `
    <tr>
      <td class="cd-t-name">${esc(bars)} sessions</td>
      <td><b>${f1(r.pct)}%</b></td>
      <td>${f1(r.controlPct)}%</td>
      <td class="${r.edge > 0 ? '' : 'cd-t-why'}"><b>${r.edge > 0 ? '+' : ''}${f1(r.edge)} pp</b></td>
      <td class="cd-t-why">${n0(r.judged)} gaps judged</td>
    </tr>`).join('');

  host.innerHTML = `
    <div class="cd-metrics">
      <span>Gaps found <b>${n0(g.gaps)}</b></span>
      <span>Bars scanned <b>${n0(g.barsScanned)}</b></span>
      <span>Per 1,000 bars <b>${f1(g.perThousandBars)}</b></span>
      <span>Median size <b>${f1(g.medianSizePct)}%</b></span>
      <span>Bullish / bearish <b>${n0(g.bullish)} / ${n0(g.bearish)}</b></span>
    </div>
    <div class="cd-table-wrap">
      <table class="cd-table">
        <thead><tr>
          <th>Within</th><th>Gaps filled</th><th>Control</th><th>Difference</th><th>Sample</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

function renderBlockTable(stats) {
  const host = document.getElementById('smc-block-table');
  const b = stats.blockTrades;
  if (!host || !b) return;

  const years = Object.keys(b.coverageByYear).sort();
  const rows = years.map(y => {
    const cov = b.coverageByYear[y];
    const dead = cov === 0;
    return `
      <tr>
        <td class="cd-t-name">${esc(y)}</td>
        <td>${n0(b.rowsByYear[y])}</td>
        <td>${n0(b.daysWithBlocksByYear[y] || 0)}</td>
        <td><b class="${dead ? 'cd-bad' : ''}">${f1(cov)}%</b></td>
        <td>${n0(b.byYear[y] || 0)}</td>
      </tr>`;
  }).join('');

  host.innerHTML = `
    <div class="cd-table-wrap">
      <table class="cd-table">
        <thead><tr>
          <th>Year</th><th>Daily bars in archive</th><th>Bars carrying a block record</th>
          <th>Coverage</th><th>Block trades counted</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

function stampGenerated(stats) {
  const el = document.getElementById('smc-generated');
  if (!el) return;
  const d = new Date(stats.generatedAt);
  el.textContent = `Figures generated ${d.toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' })}`
    + ` from ${n0(stats.archive.stocks)} stocks, ${stats.archive.dateFrom} → ${stats.archive.dateTo}.`;
}

// ─── Boot ──────────────────────────────────────────────────────
document.addEventListener('DOMContentLoaded', () => {
  drawFVGDiagram();
  drawSweepDiagram();
  loadStats();

  const links = [...document.querySelectorAll('.cd-toc a')];
  const targets = links.map(a => document.querySelector(a.getAttribute('href'))).filter(Boolean);
  if (targets.length && 'IntersectionObserver' in window) {
    const io = new IntersectionObserver(entries => {
      entries.forEach(e => {
        if (!e.isIntersecting) return;
        links.forEach(a => a.classList.toggle('active', a.getAttribute('href') === '#' + e.target.id));
      });
    }, { rootMargin: '-20% 0px -70% 0px' });
    targets.forEach(t => io.observe(t));
  }
});
